# Generated by Django 6.0.2 on 2026-02-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0017_tableorders_cloth_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablestaffs',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
