# Generated by Django 6.0.2 on 2026-02-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0018_tablestaffs_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablestaffs',
            name='daily_wage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tablestaffs',
            name='staff_type',
            field=models.CharField(choices=[('permanent', 'Permanent'), ('temporary', 'Temporary')], default='permanent', max_length=20),
        ),
    ]
