# Generated by Django 6.0.2 on 2026-02-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0019_tablestaffs_daily_wage_tablestaffs_staff_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablestaffs',
            name='monthly_salary',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
