# Generated by Django 6.0.2 on 2026-02-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0020_alter_tablestaffs_monthly_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablesalary',
            name='days_worked',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
