# Generated by Django 6.0.2 on 2026-02-12 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0021_tablesalary_days_worked'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('days_worked', models.IntegerField()),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.tablestaffs')),
            ],
            options={
                'unique_together': {('staff', 'week_start')},
            },
        ),
    ]
