# Generated by Django 6.0.2 on 2026-02-12 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0022_weeklywork'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tableorders',
            name='image',
        ),
        migrations.AlterField(
            model_name='tableorders',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='TableOrderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='orders/')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='client_app.tableorders')),
            ],
        ),
    ]
