# Generated by Django 6.0.1 on 2026-02-02 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100, null=True)),
                ('stock', models.FloatField(null=True)),
                ('unit', models.CharField(max_length=100, null=True)),
                ('notes', models.TextField(null=True)),
            ],
        ),
    ]
