# Generated by Django 6.0.1 on 2026-02-02 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablestock',
            name='low_stock',
            field=models.IntegerField(null=True),
        ),
    ]
