# Generated by Django 6.0.1 on 2026-02-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableorders',
            name='customer_id',
            field=models.CharField(null=True),
        ),
    ]
