# Generated by Django 6.0.1 on 2026-02-02 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0002_tablestaffs'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablestaffs',
            name='staffid',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='tablestaffs',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
