# Generated by Django 6.0.1 on 2026-02-02 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0003_tablestaffs_staffid_tablestaffs_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tablestaffs',
            old_name='number',
            new_name='phone',
        ),
    ]
